### ISSUE TITLE
Fake..!!! 

### ISSUE THREAD

**Issue by sujalv28** [T-Dynamos/termux-pro#2]
It's absolutely fake and useless. Not worthy to be installed. Only one command works which is math bot one (literally of no use) and that's it... It took me more than half an hour to install this, sucked all my data and presented the shit in front of me... Don't try to make us foolish by this type of shitty commands. LIAR

**Comment by T-Dynamos** [comment]
Hmm , Thanks for review can you even read the readme.md file ?
